import os

AUTOSCALER_APP_SELECTOR_NAME = os.environ.get("AUTOSCALER_APP_SELECTOR_NAME", "app")
AUTOSCALER_HIBERNATED_SERVICE_SUFFIX = os.environ.get("AUTOSCALER_HIBERNATED_SERVICE_SUFFIX", "-hibernated")
AUTOSCALER_SERVICE_EXTERNAL_NAME = os.environ.get("AUTOSCALER_SERVICE_EXTERNAL_NAME", "unip-autoscaler.unip-autoscaler")
AUTOSCALER_HEADERS_PREFIX = os.environ.get("AUTOSCALER_HEADERS_PREFIX", "<AUTOSCALER HEADERS")
AUTOSCALER_HEADERS_SUFFIX = os.environ.get("AUTOSCALER_HEADERS_SUFFIX", "AUTOSCALER HEADERS>")