apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scalingconfigs.autoscaler.unified-platform.cs.hse.ru
spec:
  group: autoscaler.unified-platform.cs.hse.ru
  names:
    kind: ScalingConfig
    plural: scalingconfigs
    shortNames:
    - scalecfg
    singular: scalingconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              prometheusMetrics:
                description: Список пользовательских метрик Prometheus, используемых в условиях
                items:
                  properties:
                    name:
                      description: Уникальное имя пользовательской метрики
                      title: Name
                      type: string
                    query:
                      description: Запрос PromQL для получения значения метрики
                      title: Query
                      type: string
                  required:
                  - name
                  - query
                  title: PrometheusMetric
                  type: object
                title: Prometheusmetrics
                type: array
              scalingOptions:
                properties:
                  cooldown:
                    description: Период (в секундах), в течение которого масштабирование отключено после предыдущего изменения
                    title: Cooldown
                    type: integer
                  cpuTimeWindow:
                    default: 300
                    description: Период усреднения метрики CPU в секундах
                    title: Cputimewindow
                    type: integer
                  hibernationEnabled:
                    description: Включение/отключение гибернации приложения
                    title: Hibernationenabled
                    type: boolean
                  memoryTimeWindow:
                    default: 300
                    description: Период усреднения метрики RAM в секундах
                    title: Memorytimewindow
                    type: integer
                required:
                - cooldown
                - hibernationEnabled
                title: ScalingOptions
                type: object
              states:
                description: Список состояний масштабирования
                items:
                  properties:
                    replicas:
                      description: Количество реплик в данном состоянии
                      title: Replicas
                      type: integer
                    transitions:
                      description: Список переходов в другие состояния из текущего
                      items:
                        properties:
                          conditions:
                            properties:
                              allConditions:
                                description: Список условий, все из которых должны быть выполнены (логическое И)
                                items:
                                  properties:
                                    metric:
                                      description: Имя метрики Prometheus (например, cpu, memory)
                                      title: Metric
                                      type: string
                                    operator:
                                      enum:
                                      - lt
                                      - gt
                                      title: Operator
                                      type: string
                                    value:
                                      description: Целевое значение метрики для выполнения условия
                                      title: Value
                                      type: number
                                  required:
                                  - metric
                                  - operator
                                  - value
                                  title: Condition
                                  type: object
                                title: Allconditions
                                type: array
                              anyCondition:
                                description: Список условий, из которых должно быть выполнено хотя бы одно (логическое ИЛИ)
                                items:
                                  properties:
                                    metric:
                                      description: Имя метрики Prometheus (например, cpu, memory)
                                      title: Metric
                                      type: string
                                    operator:
                                      enum:
                                      - lt
                                      - gt
                                      title: Operator
                                      type: string
                                    value:
                                      description: Целевое значение метрики для выполнения условия
                                      title: Value
                                      type: number
                                  required:
                                  - metric
                                  - operator
                                  - value
                                  title: Condition
                                  type: object
                                title: Anycondition
                                type: array
                            title: ConditionSet
                            type: object
                          nextState:
                            description: Количество реплик в следующем состоянии
                            title: Nextstate
                            type: integer
                        required:
                        - nextState
                        - conditions
                        title: Transition
                        type: object
                      title: Transitions
                      type: array
                  required:
                  - replicas
                  title: State
                  type: object
                title: States
                type: array
              target:
                properties:
                  kind:
                    enum:
                    - deployment
                    - service
                    title: TargetKind
                    type: string
                  name:
                    description: Имя целевого объекта масштабирования
                    title: Name
                    type: string
                  namespace:
                    description: Пространство имён, в котором находится целевой объект
                    title: Namespace
                    type: string
                required:
                - kind
                - name
                - namespace
                title: Target
                type: object
            required:
            - target
            - states
            - scalingOptions
            title: ScalingConfig
            type: object
        type: object
    served: true
    storage: true
