apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: unip-autoscaler
  name: unip-autoscaler-ingress
  namespace: unip-system-autoscaler
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /autoscaler(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: unip-autoscaler
                port:
                  number: 80