apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unip-autoscaler-cluster-role
rules:
  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      [
        "pods",
        "services",
        "secrets",
        "configmaps",
        "namespaces",
      ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io", "networking", "extensions"]
    resources: ["ingresses", "ingressclasses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: unip-system-autoscaler
  name: unip-autoscaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unip-autoscaler-sa-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unip-autoscaler-cluster-role
subjects:
  - kind: ServiceAccount
    name: unip-autoscaler
    namespace: unip-system-autoscaler
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: unip-autoscaler-sa-token
  namespace: unip-system-autoscaler
  annotations:
    kubernetes.io/service-account.name: "unip-autoscaler"
